from io import StringIO
from pathlib import Path
from uuid import UUID
import warnings

from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from pgvector.sqlalchemy import Vector
import pytest
import sqlalchemy as sa
from sqlalchemy import Engine
from sqlalchemy.exc import DBAPIError

from backend.tests.database.constraints.test_memory_constraints import (
    _insert_item_and_version, _insert_revision, _seed_domain,
)


def _config(database_url: str, output: StringIO | None = None) -> Config:
    root = Path(__file__).resolve().parents[4]
    config = Config(str(root / "backend/migrations/alembic.ini"), output_buffer=output)
    config.set_main_option("sqlalchemy.url", database_url.replace("%", "%%"))
    return config


def _legacy_embedding(engine: Engine, vector: list[float]) -> UUID:
    with engine.begin() as connection:
        domain = _seed_domain(connection, "Vector Migration")
        revision_id = _insert_revision(connection, domain, sequence_number=1)
        _, version_id, _ = _insert_item_and_version(connection, domain, revision_id)
        connection.execute(sa.text("""
            INSERT INTO memory.memory_search_embeddings (
                version_id, provider, model, dimensions, text_format_version,
                document_builder_version, source_content_hash, text_hash, embedding
            ) VALUES (:version, 'test', 'offline', :dimensions, 1, 1, :hash, :hash, :embedding)
        """), {"version": version_id, "dimensions": len(vector), "hash": "a" * 64, "embedding": vector})
    return version_id


def test_pgvector_migration_compiles_without_installing_extension() -> None:
    upgrade_sql = StringIO()
    command.upgrade(_config("postgresql+psycopg://unused@localhost/unused", upgrade_sql), "0013:0014", sql=True)
    upgrade = upgrade_sql.getvalue()
    assert "TYPE public.vector USING embedding::public.vector" in upgrade
    assert "public.vector_dims(embedding) = dimensions" in upgrade
    assert "DROP CONSTRAINT ck_memory_search_embeddings_embedding_dimensions;" in upgrade
    assert "CREATE EXTENSION" not in upgrade
    assert "CREATE INDEX" not in upgrade

    downgrade_sql = StringIO()
    command.downgrade(_config("postgresql+psycopg://unused@localhost/unused", downgrade_sql), "0014:0013", sql=True)
    assert "embedding::real[]::double precision[]" in downgrade_sql.getvalue()
    assert "DROP EXTENSION" not in downgrade_sql.getvalue()


def test_pgvector_roundtrip_preserves_rows_identity_and_canonical_history(
    database_url: str, monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("AIDAM_MIGRATION_REQUIRE_TLS", "false")
    monkeypatch.setenv("AIDAM_MIGRATION_ROLE", "aidam_owner")
    config = _config(database_url)
    command.upgrade(config, "0013")
    engine = sa.create_engine(database_url)
    vectors = [[0.125, 0.5, -0.25], [0.125] * 3072]
    ids = [_legacy_embedding(engine, vector) for vector in vectors]
    metadata_query = sa.text("""
        SELECT version_id, provider, model, dimensions, text_format_version,
               document_builder_version, source_content_hash, text_hash, indexed_at
        FROM memory.memory_search_embeddings ORDER BY dimensions
    """)
    with engine.connect() as connection:
        before = connection.execute(metadata_query).all()
        canonical = connection.execute(sa.text("SELECT * FROM memory.memory_versions ORDER BY id")).all()
    command.upgrade(config, "0014")
    with engine.connect() as connection:
        assert connection.execute(metadata_query).all() == before
        assert connection.execute(sa.text("SELECT * FROM memory.memory_versions ORDER BY id")).all() == canonical
        assert connection.execute(sa.text("""
            SELECT public.vector_dims(embedding) FROM memory.memory_search_embeddings ORDER BY dimensions
        """)).scalars().all() == [3, 3072]
        assert connection.scalar(sa.text("""
            SELECT count(*) FROM pg_catalog.pg_indexes
            WHERE schemaname = 'memory' AND tablename = 'memory_search_embeddings'
              AND (indexdef ILIKE '%USING hnsw%' OR indexdef ILIKE '%USING ivfflat%')
        """)) == 0
    for invalid in ("[1,2]", "[NaN,0,0]", "[Infinity,0,0]"):
        with pytest.raises(DBAPIError), engine.begin() as connection:
            connection.execute(sa.text("""
                UPDATE memory.memory_search_embeddings SET embedding = CAST(:vector AS public.vector)
                WHERE version_id = :version
            """), {"vector": invalid, "version": ids[0]})

    command.downgrade(config, "0013")
    with engine.connect() as connection:
        assert connection.execute(metadata_query).all() == before
        assert connection.execute(sa.text("SELECT embedding FROM memory.memory_search_embeddings ORDER BY dimensions")).scalars().all() == vectors
        assert connection.scalar(sa.text("SELECT extname FROM pg_catalog.pg_extension WHERE extname = 'vector'")) == "vector"
    command.upgrade(config, "0014")
    engine.dispose()


def test_incompatible_legacy_embedding_aborts_conversion_without_data_loss(
    database_url: str, monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("AIDAM_MIGRATION_REQUIRE_TLS", "false")
    monkeypatch.setenv("AIDAM_MIGRATION_ROLE", "aidam_owner")
    config = _config(database_url)
    command.upgrade(config, "0013")
    engine = sa.create_engine(database_url)
    _legacy_embedding(engine, [float("inf"), 0.0, 0.0])
    with pytest.raises(DBAPIError):
        command.upgrade(config, "0014")
    with engine.connect() as connection:
        assert connection.scalar(sa.text("SELECT version_num FROM public.alembic_version")) == "0013"
        assert connection.scalar(sa.text("SELECT count(*) FROM memory.memory_search_embeddings")) == 1
        assert connection.scalar(sa.text("SELECT pg_typeof(embedding)::text FROM memory.memory_search_embeddings")) == "double precision[]"
    engine.dispose()


def test_missing_extension_fails_with_provisioning_instruction(
    database_url: str, monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("AIDAM_MIGRATION_REQUIRE_TLS", "false")
    monkeypatch.setenv("AIDAM_MIGRATION_ROLE", "aidam_owner")
    config = _config(database_url)
    command.upgrade(config, "0013")
    engine = sa.create_engine(database_url)
    with engine.begin() as connection:
        connection.execute(sa.text("DROP EXTENSION vector"))
    with pytest.raises(DBAPIError, match="bootstrap_extensions.sql"):
        command.upgrade(config, "0014")
    with engine.connect() as connection:
        assert connection.scalar(sa.text("SELECT version_num FROM public.alembic_version")) == "0013"
    engine.dispose()


def test_old_extension_capability_fails_with_administrator_upgrade_instruction(
    database_url: str, monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("AIDAM_MIGRATION_REQUIRE_TLS", "false")
    monkeypatch.setenv("AIDAM_MIGRATION_ROLE", "aidam_owner")
    config = _config(database_url)
    command.upgrade(config, "0013")
    engine = sa.create_engine(database_url)
    # Simulate an older installation's absent capability only in this test DB.
    with engine.begin() as connection:
        connection.execute(sa.text("ALTER FUNCTION public.vector_norm(public.vector) RENAME TO unavailable_vector_norm"))
    with pytest.raises(DBAPIError, match="administrator must upgrade pgvector"):
        command.upgrade(config, "0014")
    with engine.connect() as connection:
        assert connection.scalar(sa.text("SELECT version_num FROM public.alembic_version")) == "0013"
    engine.dispose()


def test_qualified_vector_reflection_and_drift_detection_under_hardened_search_path(
    database_url: str, monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("AIDAM_MIGRATION_REQUIRE_TLS", "false")
    monkeypatch.setenv("AIDAM_MIGRATION_ROLE", "aidam_owner")
    config = _config(database_url)
    command.upgrade(config, "0014")
    engine = sa.create_engine(database_url)
    with warnings.catch_warnings():
        warnings.simplefilter("error", sa.exc.SAWarning)
        with engine.begin() as connection:
            connection.execute(sa.text("SET LOCAL search_path = pg_catalog"))
            columns = sa.inspect(connection).get_columns("memory_search_embeddings", schema="memory")
            embedding_type = next(column["type"] for column in columns if column["name"] == "embedding")
            assert isinstance(embedding_type, Vector)
            assert embedding_type.dim is None
        command.check(config)

        # Prove comparison is active, rather than a clean check silently skipping
        # an unknown type. This disposable DB deliberately drifts back to arrays.
        with engine.begin() as connection:
            connection.execute(sa.text("""
                ALTER TABLE memory.memory_search_embeddings
                DROP CONSTRAINT ck_memory_search_embeddings_embedding_dimensions
            """))
            connection.execute(sa.text("""
                ALTER TABLE memory.memory_search_embeddings
                ALTER COLUMN embedding TYPE double precision[]
                USING embedding::real[]::double precision[]
            """))
        with pytest.raises(AutogenerateDiffsDetected, match="modify_type"):
            command.check(config)
    engine.dispose()
