"""Pure contracts shared by datalayer workflows and later adapters."""

from backend.services.datalayer.contracts import (
    ApplyDisposition,
    CompletenessWarning,
    NormalizationStatus,
    RefreshOutcome,
    RefreshRequest,
    RefreshStatus,
    RefreshTrigger,
    RequestStatus,
    ScopeRefreshResult,
    SnapshotRequest,
    WarningCode,
)
from backend.services.datalayer.errors import (
    DatalayerError,
    DatalayerResourceNotFound,
    DatalayerScopeConflict,
    EndpointPayloadRejected,
    InternalDatalayerFailure,
    InvalidDatalayerRequest,
    SnapshotUnavailable,
)
from backend.services.datalayer.local_files import (
    LocalArtifactKind,
    LocalArtifactVerificationError,
    LocalDatalayerFileStore,
    StoredLocalArtifact,
    VerifiedLocalArtifact,
)
from backend.services.datalayer.sleeper.client import SleeperSourceClient
from backend.services.datalayer.sleeper.endpoints import (
    CompletenessFinding,
    EndpointRecords,
    LeagueEndpointRecords,
    LeagueRecord,
    LeagueUserRecord,
    LeagueUsersEndpointRecords,
    NflStateEndpointRecords,
    NflStateRecord,
    PlayerCatalogEndpointRecords,
    PlayerRecord,
    UserRecord,
    build_league_request,
    build_league_users_request,
    build_nfl_state_request,
    build_player_catalog_request,
    normalize_league,
    normalize_league_users,
    normalize_nfl_state,
    normalize_player_catalog,
    validate_league_completeness,
    validate_league_users_completeness,
    validate_nfl_state_completeness,
    validate_player_catalog_completeness,
)
from backend.services.datalayer.sleeper.responses import (
    EndpointRequest,
    FailedSourceAttempt,
    SanitizedSourceError,
    SourceAttempt,
    SuccessfulSourceAttempt,
)
from backend.services.datalayer.sleeper.scope import EndpointKind, ScopeKey
from backend.services.datalayer.versions import (
    INGESTION_NORMALIZER_VERSION,
    SNAPSHOT_PROJECTION_VERSION,
)

__all__ = [
    "ApplyDisposition",
    "CompletenessWarning",
    "CompletenessFinding",
    "DatalayerError",
    "DatalayerResourceNotFound",
    "DatalayerScopeConflict",
    "EndpointKind",
    "EndpointRecords",
    "EndpointRequest",
    "EndpointPayloadRejected",
    "FailedSourceAttempt",
    "INGESTION_NORMALIZER_VERSION",
    "InternalDatalayerFailure",
    "InvalidDatalayerRequest",
    "LocalArtifactKind",
    "LocalArtifactVerificationError",
    "LocalDatalayerFileStore",
    "LeagueEndpointRecords",
    "LeagueRecord",
    "LeagueUserRecord",
    "LeagueUsersEndpointRecords",
    "NormalizationStatus",
    "NflStateEndpointRecords",
    "NflStateRecord",
    "PlayerCatalogEndpointRecords",
    "PlayerRecord",
    "RefreshOutcome",
    "RefreshRequest",
    "RefreshStatus",
    "RefreshTrigger",
    "SanitizedSourceError",
    "RequestStatus",
    "SNAPSHOT_PROJECTION_VERSION",
    "ScopeKey",
    "ScopeRefreshResult",
    "SnapshotRequest",
    "SnapshotUnavailable",
    "SleeperSourceClient",
    "SourceAttempt",
    "StoredLocalArtifact",
    "SuccessfulSourceAttempt",
    "UserRecord",
    "VerifiedLocalArtifact",
    "WarningCode",
    "build_league_request",
    "build_league_users_request",
    "build_nfl_state_request",
    "build_player_catalog_request",
    "normalize_league",
    "normalize_league_users",
    "normalize_nfl_state",
    "normalize_player_catalog",
    "validate_league_completeness",
    "validate_league_users_completeness",
    "validate_nfl_state_completeness",
    "validate_player_catalog_completeness",
]
