"""cross namespace integrity

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-09 00:08:18.531504
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _create_receipt_scope_guards() -> None:
    op.execute(
        """
        CREATE FUNCTION memory.enforce_api_receipt_competition()
        RETURNS trigger LANGUAGE plpgsql AS $memory$
        BEGIN
            IF NEW.primary_api_request_id IS NOT NULL AND EXISTS (
                SELECT 1
                FROM sleeper.api_requests AS request
                JOIN core.competition_seasons AS season
                  ON season.id = request.competition_season_id
                WHERE request.id = NEW.primary_api_request_id
                  AND season.competition_id <> NEW.competition_id
            ) THEN
                RAISE EXCEPTION 'API receipt belongs to another competition';
            END IF;
            RETURN NEW;
        END;
        $memory$
        """
    )
    for table_name in ("fact_versions", "event_versions"):
        op.execute(
            f"""
            CREATE TRIGGER {table_name}_enforce_api_receipt_competition
            BEFORE INSERT ON memory.{table_name}
            FOR EACH ROW EXECUTE FUNCTION memory.enforce_api_receipt_competition()
            """
        )


def _drop_receipt_scope_guards() -> None:
    op.execute("DROP FUNCTION memory.enforce_api_receipt_competition() CASCADE")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_versions', sa.Column('competition_id', sa.UUID(), nullable=False), schema='memory')
    op.add_column('event_versions', sa.Column('primary_tool_call_generation_id', sa.UUID(), nullable=True), schema='memory')
    op.drop_index(op.f('ix_event_versions_primary_tool_call'), table_name='event_versions', schema='memory')
    op.create_index('ix_event_versions_primary_tool_call', 'event_versions', ['primary_tool_call_id', 'primary_tool_call_generation_id'], unique=False, schema='memory')
    op.create_index('ix_event_versions_tool_generation_competition', 'event_versions', ['primary_tool_call_generation_id', 'competition_id'], unique=False, schema='memory')
    op.drop_constraint(op.f('fk_event_versions_version_id_memory_versions'), 'event_versions', schema='memory', type_='foreignkey')
    op.create_foreign_key('fk_event_versions_version_same_competition', 'event_versions', 'memory_versions', ['version_id', 'competition_id'], ['id', 'competition_id'], source_schema='memory', referent_schema='memory', ondelete='RESTRICT')
    op.create_foreign_key('fk_event_versions_tool_call_same_generation', 'event_versions', 'tool_calls', ['primary_tool_call_id', 'primary_tool_call_generation_id'], ['id', 'generation_id'], source_schema='memory', referent_schema='reporting', ondelete='RESTRICT', use_alter=True, match='FULL')
    op.create_foreign_key('fk_event_versions_tool_generation_same_competition', 'event_versions', 'generations', ['primary_tool_call_generation_id', 'competition_id'], ['id', 'competition_id'], source_schema='memory', referent_schema='reporting', ondelete='RESTRICT', use_alter=True)
    op.add_column('fact_versions', sa.Column('competition_id', sa.UUID(), nullable=False), schema='memory')
    op.add_column('fact_versions', sa.Column('primary_tool_call_generation_id', sa.UUID(), nullable=True), schema='memory')
    op.drop_index(op.f('ix_fact_versions_primary_tool_call'), table_name='fact_versions', schema='memory')
    op.create_index('ix_fact_versions_primary_tool_call', 'fact_versions', ['primary_tool_call_id', 'primary_tool_call_generation_id'], unique=False, schema='memory')
    op.create_index('ix_fact_versions_tool_generation_competition', 'fact_versions', ['primary_tool_call_generation_id', 'competition_id'], unique=False, schema='memory')
    op.drop_constraint(op.f('fk_fact_versions_version_id_memory_versions'), 'fact_versions', schema='memory', type_='foreignkey')
    op.create_foreign_key('fk_fact_versions_tool_call_same_generation', 'fact_versions', 'tool_calls', ['primary_tool_call_id', 'primary_tool_call_generation_id'], ['id', 'generation_id'], source_schema='memory', referent_schema='reporting', ondelete='RESTRICT', use_alter=True, match='FULL')
    op.create_foreign_key('fk_fact_versions_version_same_competition', 'fact_versions', 'memory_versions', ['version_id', 'competition_id'], ['id', 'competition_id'], source_schema='memory', referent_schema='memory', ondelete='RESTRICT')
    op.create_foreign_key('fk_fact_versions_tool_generation_same_competition', 'fact_versions', 'generations', ['primary_tool_call_generation_id', 'competition_id'], ['id', 'competition_id'], source_schema='memory', referent_schema='reporting', ondelete='RESTRICT', use_alter=True)
    op.drop_index(op.f('ix_memory_revisions_producing_generation'), table_name='memory_revisions', schema='memory')
    op.create_index('ix_memory_revisions_producing_generation', 'memory_revisions', ['producing_generation_id', 'competition_id'], unique=False, schema='memory')
    op.create_foreign_key('fk_memory_revisions_generation_same_competition', 'memory_revisions', 'generations', ['producing_generation_id', 'competition_id'], ['id', 'competition_id'], source_schema='memory', referent_schema='reporting', ondelete='RESTRICT', use_alter=True)
    op.drop_index(op.f('ix_memory_versions_creating_generation'), table_name='memory_versions', schema='memory')
    op.create_index('ix_memory_versions_creating_generation', 'memory_versions', ['creating_generation_id', 'competition_id'], unique=False, schema='memory')
    op.create_index('ix_memory_versions_creating_tool_call', 'memory_versions', ['creating_tool_call_id', 'creating_generation_id'], unique=False, schema='memory')
    op.create_foreign_key('fk_memory_versions_tool_call_same_generation', 'memory_versions', 'tool_calls', ['creating_tool_call_id', 'creating_generation_id'], ['id', 'generation_id'], source_schema='memory', referent_schema='reporting', ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key('fk_memory_versions_generation_same_competition', 'memory_versions', 'generations', ['creating_generation_id', 'competition_id'], ['id', 'competition_id'], source_schema='memory', referent_schema='reporting', ondelete='RESTRICT', use_alter=True)
    op.add_column('generations', sa.Column('input_memory_artifact_generation_id', sa.UUID(), nullable=True), schema='reporting')
    op.create_unique_constraint('uq_generations_id_workspace_competition', 'generations', ['id', 'evaluation_workspace_id', 'competition_id'], schema='reporting')
    op.drop_index(op.f('ix_generations_data_snapshot'), table_name='generations', schema='reporting')
    op.create_index('ix_generations_data_snapshot', 'generations', ['data_snapshot_id', 'competition_season_id'], unique=False, schema='reporting')
    op.create_foreign_key('fk_generations_snapshot_same_season', 'generations', 'data_snapshots', ['data_snapshot_id', 'competition_season_id'], ['id', 'primary_competition_season_id'], source_schema='reporting', referent_schema='sleeper', ondelete='RESTRICT')
    op.drop_constraint(op.f('ck_generations_unambiguous_memory_input'), 'generations', schema='reporting', type_='check')
    op.create_check_constraint(
        op.f('ck_generations_unambiguous_memory_input'),
        'generations',
        "num_nonnulls(input_memory_revision_id, input_memory_artifact_version_id) <= 1 "
        "AND ((input_memory_artifact_version_id IS NULL AND "
        "input_memory_artifact_generation_id IS NULL) OR "
        "(input_memory_artifact_version_id IS NOT NULL AND "
        "input_memory_artifact_generation_id IS NOT NULL AND "
        "evaluation_workspace_id IS NOT NULL))",
        schema='reporting',
    )
    op.add_column('evaluation_workspaces', sa.Column('current_memory_artifact_generation_id', sa.UUID(), nullable=True), schema='reporting')
    op.create_index('ix_evaluation_workspaces_current_artifact', 'evaluation_workspaces', ['current_memory_artifact_version_id', 'current_memory_artifact_generation_id'], unique=False, schema='reporting')
    op.create_index('ix_evaluation_workspaces_current_artifact_workspace', 'evaluation_workspaces', ['current_memory_artifact_generation_id', 'id', 'competition_id'], unique=False, schema='reporting')
    op.create_foreign_key('fk_evaluation_workspaces_current_artifact_workspace_scope', 'evaluation_workspaces', 'generations', ['current_memory_artifact_generation_id', 'id', 'competition_id'], ['id', 'evaluation_workspace_id', 'competition_id'], source_schema='reporting', referent_schema='reporting', ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key('fk_evaluation_workspaces_current_artifact_same_generation', 'evaluation_workspaces', 'artifact_versions', ['current_memory_artifact_version_id', 'current_memory_artifact_generation_id'], ['id', 'generation_id'], source_schema='reporting', referent_schema='reporting', ondelete='RESTRICT', use_alter=True, match='FULL')
    op.create_index('ix_generations_input_artifact', 'generations', ['input_memory_artifact_version_id', 'input_memory_artifact_generation_id'], unique=False, schema='reporting')
    op.create_index('ix_generations_input_artifact_workspace', 'generations', ['input_memory_artifact_generation_id', 'evaluation_workspace_id', 'competition_id'], unique=False, schema='reporting')
    op.create_foreign_key('fk_generations_input_artifact_same_generation', 'generations', 'artifact_versions', ['input_memory_artifact_version_id', 'input_memory_artifact_generation_id'], ['id', 'generation_id'], source_schema='reporting', referent_schema='reporting', ondelete='RESTRICT', use_alter=True, match='FULL')
    op.create_foreign_key('fk_generations_input_artifact_workspace_scope', 'generations', 'generations', ['input_memory_artifact_generation_id', 'evaluation_workspace_id', 'competition_id'], ['id', 'evaluation_workspace_id', 'competition_id'], source_schema='reporting', referent_schema='reporting', ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key('fk_api_requests_payload', 'api_requests', 'api_payloads', ['payload_id'], ['id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.create_foreign_key('fk_api_requests_refresh_run', 'api_requests', 'refresh_runs', ['refresh_run_id'], ['id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.add_column('draft_picks', sa.Column('source_api_request_competition_season_id', sa.UUID(), nullable=True), schema='sleeper')
    op.create_index('ix_draft_picks_source_request_competition', 'draft_picks', ['source_api_request_competition_season_id', 'competition_id'], unique=False, schema='sleeper')
    op.create_index('ix_draft_picks_source_request_scope', 'draft_picks', ['source_api_request_id', 'source_api_request_competition_season_id'], unique=False, schema='sleeper')
    op.drop_constraint(op.f('fk_draft_picks_source_api_request_id_api_requests'), 'draft_picks', schema='sleeper', type_='foreignkey')
    op.create_foreign_key('fk_draft_picks_source_request_scope', 'draft_picks', 'api_requests', ['source_api_request_id', 'source_api_request_competition_season_id'], ['id', 'competition_season_id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT', match='FULL')
    op.create_foreign_key('fk_draft_picks_source_request_same_competition', 'draft_picks', 'competition_seasons', ['source_api_request_competition_season_id', 'competition_id'], ['id', 'competition_id'], source_schema='sleeper', referent_schema='core', ondelete='RESTRICT')
    op.create_index('ix_league_users_source_request_scope', 'league_users', ['source_api_request_id', 'competition_season_id'], unique=False, schema='sleeper')
    op.drop_constraint(op.f('fk_league_users_source_api_request_id_api_requests'), 'league_users', schema='sleeper', type_='foreignkey')
    op.create_foreign_key('fk_league_users_source_request_scope', 'league_users', 'api_requests', ['source_api_request_id', 'competition_season_id'], ['id', 'competition_season_id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.drop_index(op.f('ix_leagues_source_request'), table_name='leagues', schema='sleeper')
    op.create_index('ix_leagues_source_request', 'leagues', ['source_api_request_id', 'competition_season_id'], unique=False, schema='sleeper')
    op.drop_constraint(op.f('fk_leagues_source_api_request_id_api_requests'), 'leagues', schema='sleeper', type_='foreignkey')
    op.create_foreign_key('fk_leagues_source_request_scope', 'leagues', 'api_requests', ['source_api_request_id', 'competition_season_id'], ['id', 'competition_season_id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.create_index('ix_matchups_source_request_scope', 'matchups', ['source_api_request_id', 'competition_season_id'], unique=False, schema='sleeper')
    op.drop_constraint(op.f('fk_matchups_source_api_request_id_api_requests'), 'matchups', schema='sleeper', type_='foreignkey')
    op.create_foreign_key('fk_matchups_source_request_scope', 'matchups', 'api_requests', ['source_api_request_id', 'competition_season_id'], ['id', 'competition_season_id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.create_index('ix_player_performances_source_request_scope', 'player_performances', ['source_api_request_id', 'competition_season_id'], unique=False, schema='sleeper')
    op.drop_constraint(op.f('fk_player_performances_source_api_request_id_api_requests'), 'player_performances', schema='sleeper', type_='foreignkey')
    op.create_foreign_key('fk_player_performances_source_request_scope', 'player_performances', 'api_requests', ['source_api_request_id', 'competition_season_id'], ['id', 'competition_season_id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.create_index('ix_playoff_matchups_source_request_scope', 'playoff_matchups', ['source_api_request_id', 'competition_season_id'], unique=False, schema='sleeper')
    op.drop_constraint(op.f('fk_playoff_matchups_source_api_request_id_api_requests'), 'playoff_matchups', schema='sleeper', type_='foreignkey')
    op.create_foreign_key('fk_playoff_matchups_source_request_scope', 'playoff_matchups', 'api_requests', ['source_api_request_id', 'competition_season_id'], ['id', 'competition_season_id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.create_unique_constraint('uq_rosters_id_competition_season', 'rosters', ['season_roster_id', 'competition_season_id'], schema='sleeper')
    op.add_column('roster_managers', sa.Column('competition_season_id', sa.UUID(), nullable=False), schema='sleeper')
    op.create_index('ix_roster_managers_roster_scope', 'roster_managers', ['season_roster_id', 'competition_season_id'], unique=False, schema='sleeper')
    op.create_index('ix_roster_managers_source_request_scope', 'roster_managers', ['source_api_request_id', 'competition_season_id'], unique=False, schema='sleeper')
    op.drop_constraint(op.f('fk_roster_managers_season_roster_id_rosters'), 'roster_managers', schema='sleeper', type_='foreignkey')
    op.drop_constraint(op.f('fk_roster_managers_source_api_request_id_api_requests'), 'roster_managers', schema='sleeper', type_='foreignkey')
    op.create_foreign_key('fk_roster_managers_source_request_scope', 'roster_managers', 'api_requests', ['source_api_request_id', 'competition_season_id'], ['id', 'competition_season_id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.create_foreign_key('fk_roster_managers_roster_scope', 'roster_managers', 'rosters', ['season_roster_id', 'competition_season_id'], ['season_roster_id', 'competition_season_id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.add_column('roster_players', sa.Column('competition_season_id', sa.UUID(), nullable=False), schema='sleeper')
    op.create_index('ix_roster_players_roster_scope', 'roster_players', ['season_roster_id', 'competition_season_id'], unique=False, schema='sleeper')
    op.create_index('ix_roster_players_source_request_scope', 'roster_players', ['source_api_request_id', 'competition_season_id'], unique=False, schema='sleeper')
    op.drop_constraint(op.f('fk_roster_players_season_roster_id_rosters'), 'roster_players', schema='sleeper', type_='foreignkey')
    op.drop_constraint(op.f('fk_roster_players_source_api_request_id_api_requests'), 'roster_players', schema='sleeper', type_='foreignkey')
    op.create_foreign_key('fk_roster_players_source_request_scope', 'roster_players', 'api_requests', ['source_api_request_id', 'competition_season_id'], ['id', 'competition_season_id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.create_foreign_key('fk_roster_players_roster_scope', 'roster_players', 'rosters', ['season_roster_id', 'competition_season_id'], ['season_roster_id', 'competition_season_id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.create_index('ix_rosters_source_request_scope', 'rosters', ['source_api_request_id', 'competition_season_id'], unique=False, schema='sleeper')
    op.drop_constraint(op.f('fk_rosters_source_api_request_id_api_requests'), 'rosters', schema='sleeper', type_='foreignkey')
    op.create_foreign_key('fk_rosters_source_request_scope', 'rosters', 'api_requests', ['source_api_request_id', 'competition_season_id'], ['id', 'competition_season_id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.add_column('transaction_moves', sa.Column('competition_id', sa.UUID(), nullable=False), schema='sleeper')
    op.drop_index(op.f('ix_transaction_moves_pick'), table_name='transaction_moves', schema='sleeper')
    op.create_index('ix_transaction_moves_pick', 'transaction_moves', ['draft_pick_id', 'competition_id'], unique=False, schema='sleeper')
    op.create_index('ix_transaction_moves_season_competition', 'transaction_moves', ['competition_season_id', 'competition_id'], unique=False, schema='sleeper')
    op.drop_constraint(op.f('fk_transaction_moves_draft_pick_id_draft_picks'), 'transaction_moves', schema='sleeper', type_='foreignkey')
    op.create_foreign_key('fk_transaction_moves_draft_pick_same_competition', 'transaction_moves', 'draft_picks', ['draft_pick_id', 'competition_id'], ['id', 'competition_id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.create_foreign_key('fk_transaction_moves_season_same_competition', 'transaction_moves', 'competition_seasons', ['competition_season_id', 'competition_id'], ['id', 'competition_id'], source_schema='sleeper', referent_schema='core', ondelete='RESTRICT')
    op.create_index('ix_transactions_source_request_scope', 'transactions', ['source_api_request_id', 'competition_season_id'], unique=False, schema='sleeper')
    op.drop_constraint(op.f('fk_transactions_source_api_request_id_api_requests'), 'transactions', schema='sleeper', type_='foreignkey')
    op.create_foreign_key('fk_transactions_source_request_scope', 'transactions', 'api_requests', ['source_api_request_id', 'competition_season_id'], ['id', 'competition_season_id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    _create_receipt_scope_guards()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_receipt_scope_guards()
    op.drop_constraint('fk_transactions_source_request_scope', 'transactions', schema='sleeper', type_='foreignkey')
    op.create_foreign_key(op.f('fk_transactions_source_api_request_id_api_requests'), 'transactions', 'api_requests', ['source_api_request_id'], ['id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.drop_index('ix_transactions_source_request_scope', table_name='transactions', schema='sleeper')
    op.drop_constraint('fk_transaction_moves_season_same_competition', 'transaction_moves', schema='sleeper', type_='foreignkey')
    op.drop_constraint('fk_transaction_moves_draft_pick_same_competition', 'transaction_moves', schema='sleeper', type_='foreignkey')
    op.create_foreign_key(op.f('fk_transaction_moves_draft_pick_id_draft_picks'), 'transaction_moves', 'draft_picks', ['draft_pick_id'], ['id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.drop_index('ix_transaction_moves_season_competition', table_name='transaction_moves', schema='sleeper')
    op.drop_index('ix_transaction_moves_pick', table_name='transaction_moves', schema='sleeper')
    op.create_index(op.f('ix_transaction_moves_pick'), 'transaction_moves', ['draft_pick_id'], unique=False, schema='sleeper')
    op.drop_column('transaction_moves', 'competition_id', schema='sleeper')
    op.drop_constraint('fk_rosters_source_request_scope', 'rosters', schema='sleeper', type_='foreignkey')
    op.create_foreign_key(op.f('fk_rosters_source_api_request_id_api_requests'), 'rosters', 'api_requests', ['source_api_request_id'], ['id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.drop_index('ix_rosters_source_request_scope', table_name='rosters', schema='sleeper')
    op.drop_constraint('fk_roster_players_roster_scope', 'roster_players', schema='sleeper', type_='foreignkey')
    op.drop_constraint('fk_roster_players_source_request_scope', 'roster_players', schema='sleeper', type_='foreignkey')
    op.create_foreign_key(op.f('fk_roster_players_source_api_request_id_api_requests'), 'roster_players', 'api_requests', ['source_api_request_id'], ['id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_roster_players_season_roster_id_rosters'), 'roster_players', 'rosters', ['season_roster_id'], ['season_roster_id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.drop_index('ix_roster_players_source_request_scope', table_name='roster_players', schema='sleeper')
    op.drop_index('ix_roster_players_roster_scope', table_name='roster_players', schema='sleeper')
    op.drop_column('roster_players', 'competition_season_id', schema='sleeper')
    op.drop_constraint('fk_roster_managers_roster_scope', 'roster_managers', schema='sleeper', type_='foreignkey')
    op.drop_constraint('fk_roster_managers_source_request_scope', 'roster_managers', schema='sleeper', type_='foreignkey')
    op.create_foreign_key(op.f('fk_roster_managers_source_api_request_id_api_requests'), 'roster_managers', 'api_requests', ['source_api_request_id'], ['id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_roster_managers_season_roster_id_rosters'), 'roster_managers', 'rosters', ['season_roster_id'], ['season_roster_id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.drop_index('ix_roster_managers_source_request_scope', table_name='roster_managers', schema='sleeper')
    op.drop_index('ix_roster_managers_roster_scope', table_name='roster_managers', schema='sleeper')
    op.drop_column('roster_managers', 'competition_season_id', schema='sleeper')
    op.drop_constraint('uq_rosters_id_competition_season', 'rosters', schema='sleeper', type_='unique')
    op.drop_constraint('fk_playoff_matchups_source_request_scope', 'playoff_matchups', schema='sleeper', type_='foreignkey')
    op.create_foreign_key(op.f('fk_playoff_matchups_source_api_request_id_api_requests'), 'playoff_matchups', 'api_requests', ['source_api_request_id'], ['id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.drop_index('ix_playoff_matchups_source_request_scope', table_name='playoff_matchups', schema='sleeper')
    op.drop_constraint('fk_player_performances_source_request_scope', 'player_performances', schema='sleeper', type_='foreignkey')
    op.create_foreign_key(op.f('fk_player_performances_source_api_request_id_api_requests'), 'player_performances', 'api_requests', ['source_api_request_id'], ['id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.drop_index('ix_player_performances_source_request_scope', table_name='player_performances', schema='sleeper')
    op.drop_constraint('fk_matchups_source_request_scope', 'matchups', schema='sleeper', type_='foreignkey')
    op.create_foreign_key(op.f('fk_matchups_source_api_request_id_api_requests'), 'matchups', 'api_requests', ['source_api_request_id'], ['id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.drop_index('ix_matchups_source_request_scope', table_name='matchups', schema='sleeper')
    op.drop_constraint('fk_leagues_source_request_scope', 'leagues', schema='sleeper', type_='foreignkey')
    op.create_foreign_key(op.f('fk_leagues_source_api_request_id_api_requests'), 'leagues', 'api_requests', ['source_api_request_id'], ['id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.drop_index('ix_leagues_source_request', table_name='leagues', schema='sleeper')
    op.create_index(op.f('ix_leagues_source_request'), 'leagues', ['source_api_request_id'], unique=False, schema='sleeper')
    op.drop_constraint('fk_league_users_source_request_scope', 'league_users', schema='sleeper', type_='foreignkey')
    op.create_foreign_key(op.f('fk_league_users_source_api_request_id_api_requests'), 'league_users', 'api_requests', ['source_api_request_id'], ['id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.drop_index('ix_league_users_source_request_scope', table_name='league_users', schema='sleeper')
    op.drop_constraint('fk_draft_picks_source_request_same_competition', 'draft_picks', schema='sleeper', type_='foreignkey')
    op.drop_constraint('fk_draft_picks_source_request_scope', 'draft_picks', schema='sleeper', type_='foreignkey')
    op.create_foreign_key(op.f('fk_draft_picks_source_api_request_id_api_requests'), 'draft_picks', 'api_requests', ['source_api_request_id'], ['id'], source_schema='sleeper', referent_schema='sleeper', ondelete='RESTRICT')
    op.drop_index('ix_draft_picks_source_request_scope', table_name='draft_picks', schema='sleeper')
    op.drop_index('ix_draft_picks_source_request_competition', table_name='draft_picks', schema='sleeper')
    op.drop_column('draft_picks', 'source_api_request_competition_season_id', schema='sleeper')
    op.drop_constraint('fk_api_requests_refresh_run', 'api_requests', schema='sleeper', type_='foreignkey')
    op.drop_constraint('fk_api_requests_payload', 'api_requests', schema='sleeper', type_='foreignkey')
    op.drop_constraint('fk_generations_input_artifact_workspace_scope', 'generations', schema='reporting', type_='foreignkey')
    op.drop_constraint('fk_generations_input_artifact_same_generation', 'generations', schema='reporting', type_='foreignkey')
    op.drop_constraint('fk_generations_snapshot_same_season', 'generations', schema='reporting', type_='foreignkey')
    op.drop_index('ix_generations_data_snapshot', table_name='generations', schema='reporting')
    op.create_index(op.f('ix_generations_data_snapshot'), 'generations', ['data_snapshot_id'], unique=False, schema='reporting')
    op.drop_constraint('fk_evaluation_workspaces_current_artifact_same_generation', 'evaluation_workspaces', schema='reporting', type_='foreignkey')
    op.drop_constraint('fk_evaluation_workspaces_current_artifact_workspace_scope', 'evaluation_workspaces', schema='reporting', type_='foreignkey')
    op.drop_index('ix_evaluation_workspaces_current_artifact_workspace', table_name='evaluation_workspaces', schema='reporting')
    op.drop_index('ix_evaluation_workspaces_current_artifact', table_name='evaluation_workspaces', schema='reporting')
    op.drop_column('evaluation_workspaces', 'current_memory_artifact_generation_id', schema='reporting')
    op.drop_constraint(op.f('ck_generations_unambiguous_memory_input'), 'generations', schema='reporting', type_='check')
    op.create_check_constraint(
        op.f('ck_generations_unambiguous_memory_input'),
        'generations',
        'num_nonnulls(input_memory_revision_id, input_memory_artifact_version_id) <= 1',
        schema='reporting',
    )
    op.drop_constraint('uq_generations_id_workspace_competition', 'generations', schema='reporting', type_='unique')
    op.drop_index('ix_generations_input_artifact_workspace', table_name='generations', schema='reporting')
    op.drop_index('ix_generations_input_artifact', table_name='generations', schema='reporting')
    op.drop_column('generations', 'input_memory_artifact_generation_id', schema='reporting')
    op.drop_constraint('fk_memory_versions_generation_same_competition', 'memory_versions', schema='memory', type_='foreignkey')
    op.drop_constraint('fk_memory_versions_tool_call_same_generation', 'memory_versions', schema='memory', type_='foreignkey')
    op.drop_index('ix_memory_versions_creating_tool_call', table_name='memory_versions', schema='memory')
    op.drop_index('ix_memory_versions_creating_generation', table_name='memory_versions', schema='memory')
    op.create_index(op.f('ix_memory_versions_creating_generation'), 'memory_versions', ['creating_generation_id'], unique=False, schema='memory')
    op.drop_constraint('fk_memory_revisions_generation_same_competition', 'memory_revisions', schema='memory', type_='foreignkey')
    op.drop_index('ix_memory_revisions_producing_generation', table_name='memory_revisions', schema='memory')
    op.create_index(op.f('ix_memory_revisions_producing_generation'), 'memory_revisions', ['producing_generation_id'], unique=False, schema='memory')
    op.drop_constraint('fk_fact_versions_tool_generation_same_competition', 'fact_versions', schema='memory', type_='foreignkey')
    op.drop_constraint('fk_fact_versions_version_same_competition', 'fact_versions', schema='memory', type_='foreignkey')
    op.drop_constraint('fk_fact_versions_tool_call_same_generation', 'fact_versions', schema='memory', type_='foreignkey')
    op.create_foreign_key(op.f('fk_fact_versions_version_id_memory_versions'), 'fact_versions', 'memory_versions', ['version_id'], ['id'], source_schema='memory', referent_schema='memory', ondelete='RESTRICT')
    op.drop_index('ix_fact_versions_tool_generation_competition', table_name='fact_versions', schema='memory')
    op.drop_index('ix_fact_versions_primary_tool_call', table_name='fact_versions', schema='memory')
    op.create_index(op.f('ix_fact_versions_primary_tool_call'), 'fact_versions', ['primary_tool_call_id'], unique=False, schema='memory')
    op.drop_column('fact_versions', 'primary_tool_call_generation_id', schema='memory')
    op.drop_column('fact_versions', 'competition_id', schema='memory')
    op.drop_constraint('fk_event_versions_tool_generation_same_competition', 'event_versions', schema='memory', type_='foreignkey')
    op.drop_constraint('fk_event_versions_tool_call_same_generation', 'event_versions', schema='memory', type_='foreignkey')
    op.drop_constraint('fk_event_versions_version_same_competition', 'event_versions', schema='memory', type_='foreignkey')
    op.create_foreign_key(op.f('fk_event_versions_version_id_memory_versions'), 'event_versions', 'memory_versions', ['version_id'], ['id'], source_schema='memory', referent_schema='memory', ondelete='RESTRICT')
    op.drop_index('ix_event_versions_tool_generation_competition', table_name='event_versions', schema='memory')
    op.drop_index('ix_event_versions_primary_tool_call', table_name='event_versions', schema='memory')
    op.create_index(op.f('ix_event_versions_primary_tool_call'), 'event_versions', ['primary_tool_call_id'], unique=False, schema='memory')
    op.drop_column('event_versions', 'primary_tool_call_generation_id', schema='memory')
    op.drop_column('event_versions', 'competition_id', schema='memory')
    # ### end Alembic commands ###
